# Generated by Django 2.1.5 on 2021-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='munro',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
