# Generated by Django 2.1.5 on 2021-08-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_munro_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='bagged',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
