# Generated by Django 2.1.5 on 2021-08-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210805_2005'),
        ('rango', '0002_auto_20210805_1342'),
    ]

    operations = [
    ]
