# Generated by Django 2.1.5 on 2021-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_merge_20210805_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_slug', models.CharField(max_length=128, unique=True)),
                ('user_id', models.IntegerField(default=0)),
                ('has_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
