# Generated by Django 2.1.5 on 2021-08-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_munro_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munro',
            name='images',
            field=models.CharField(default='', max_length=128),
        ),
    ]
