# Generated by Django 2.1.5 on 2021-08-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_userlikearea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLikeArea',
        ),
    ]
