# Generated by Django 2.1.5 on 2021-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210804_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='munro',
            old_name='images',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='munro',
            name='image_2',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
