# Generated by Django 2.1.5 on 2021-08-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bagged', models.CharField(default='', max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hikers',
            },
        ),
        migrations.CreateModel(
            name='Munro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='Munro_Images')),
                ('difficulty', models.IntegerField(default=0)),
                ('elevation', models.IntegerField(default=0)),
                ('coordinates', models.CharField(default='', max_length=128)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Area')),
            ],
            options={
                'verbose_name_plural': 'Munros',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='report_images')),
                ('difficulty', models.IntegerField(default=0)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Hiker')),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Munro')),
            ],
        ),
    ]
