# Generated by Django 2.1.5 on 2021-08-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20210804_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='munro',
            name='image_3',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
