# Generated by Django 2.1.5 on 2021-08-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_area_hiker_munro_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='munro',
            name='munroarea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rango.Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='munro',
            name='area',
            field=models.CharField(default='', max_length=128),
        ),
    ]
