# Generated by Django 2.1.5 on 2021-08-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20210804_2251'),
        ('rango', '0008_munro_image_3'),
    ]

    operations = [
    ]
