# Generated by Django 2.1.5 on 2021-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210802_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_text',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
