# Generated by Django 2.1.5 on 2021-08-05 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_merge_20210805_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='bagged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Munro'),
        ),
    ]
