# Generated by Django 2.1.5 on 2021-08-05 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0012_auto_20210805_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggedMunros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Munro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='hiker',
            name='bagged',
        ),
        migrations.AddField(
            model_name='hiker',
            name='bagged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.BaggedMunros'),
        ),
    ]
