# Generated by Django 2.1.5 on 2021-08-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20210805_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggedmunros',
            options={'verbose_name_plural': 'Bagged Munros'},
        ),
    ]
