# Generated by Django 2.1.5 on 2021-08-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20210805_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baggedmunros',
            name='munro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.Munro'),
        ),
    ]
