# Generated by Django 2.1.5 on 2021-08-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_auto_20210805_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baggedmunros',
            old_name='on',
            new_name='hiker_key',
        ),
    ]
