# Generated by Django 2.1.5 on 2021-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20210805_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='bagged',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
